---
title: "Functions to simulate data sets"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Functions to simulate data sets}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(quollr)
```

```{r, message=FALSE}
gaussian_clusters_df <- gaussian_clusters(n = 300, with_seed = 123, num_clusters = 3, mean_matrix = rbind(c(1,0,0), c(0,1,0), c(0,0,1)), var_vec = c(0.05, 0.05, 0.05), num_dims = 3, num_noise_dims = 2, min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(gaussian_clusters_df)
```

```{r, message=FALSE}
s_curve_df <- s_curve_with_noise_dims(n = 200, with_seed = NULL, num_noise_dims = 3,
                               min_noise = -0.5, max_noise = 0.5)

langevitour::langevitour(s_curve_df)
```

```{r, message=FALSE}
triangular_plane_with_noise_df <- triangular_plane_with_bkg_noise(sample_size = 675, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)
    
langevitour::langevitour(triangular_plane_with_noise_df)
```

```{r, message=FALSE}
two_curvilinear_with_noise_dims_df <- two_curvilinear_with_noise(sample_size = 100, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)
    
langevitour::langevitour(two_curvilinear_with_noise_dims_df)
```

```{r, message=FALSE}
two_curvilinear_diff_df <- two_curvilinear_diff_with_noise(sample_size = 100, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)
    
langevitour::langevitour(two_curvilinear_diff_df)
```

```{r, message=FALSE}
two_linear_diff_df <- two_linear_diff_with_noise(sample_size = 150, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(two_linear_diff_df)
```

```{r, message=FALSE}
plane_df <- plane_2D(sample_size = 300, with_seed = 2023062801)

langevitour::langevitour(plane_df)
```

```{r, message=FALSE}
curvilinear_df <- curvilinear_2D(sample_size = 300, with_seed = 2023062801)

langevitour::langevitour(curvilinear_df)
```

```{r, message=FALSE}
cube <- cube_3D_with_noise(with_seed = 2023062801)

cube_df <- cube$df

sample_size <- cube$sample_size

langevitour::langevitour(cube_df)
```

```{r, message=FALSE}
nonlinear_df <- nonlinear_2D(sample_size = 250, with_seed = 2023062801, num_of_noise_dim = 5, min_noise = -0.1, max_noise = 0.2)

langevitour::langevitour(nonlinear_df)
```

```{r, message=FALSE}
clusters_diff_df <- clusters_different_shapes(with_seed = 2023062801)

langevitour::langevitour(clusters_diff_df)
```

```{r, message=FALSE}
dataset9 <- three_clusters_data_with_noise(sample_size = 300, num_of_noise_dim = 3)

langevitour::langevitour(dataset9)
```

```{r, message=FALSE}
dataset10 <- torus_with_noise(sample_size = 300, num_of_noise_dim = 4)

langevitour::langevitour(dataset10)
```

```{r, message=FALSE}
dataset11 <- spiral_with_noise(sample_size = 300, num_of_noise_dim = 4)

langevitour::langevitour(dataset11)
```

```{r, message=FALSE}
dataset12 <- roman_surface_with_noise(sample_size = 300, num_of_noise_dim = 3, min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset12)
```

```{r, message=FALSE}
dataset13 <- mobius_with_noise(sample_size = 300, num_of_noise_dim = 3)

langevitour::langevitour(dataset13)
```

```{r, message=FALSE}
dataset14 <- dini_surface_with_noise(sample_size = 300, num_of_noise_dim = 3)

langevitour::langevitour(dataset14)
```

```{r, message=FALSE}
dataset15 <- conic_spiral_with_noise(sample_size = 300, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset15)
```

```{r, message=FALSE}
dataset16 <- s_curve_data_hole_with_noise(sample_size = 300, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)$df

s_curve_data_hole_with_noise(sample_size = 300, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)$sample_size

langevitour::langevitour(dataset16)
```

```{r, message=FALSE}
dataset17 <- long_cluster_with_noise(sample_size = 300, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)


langevitour::langevitour(dataset17)
```

```{r, message=FALSE}
dataset18 <- nonlinear_connect_with_noise(sample_size = 400, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)


langevitour::langevitour(dataset18)
```

```{r, message=FALSE}
dataset19 <- nonlinear_mirror_with_noise(sample_size = 400, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)


langevitour::langevitour(dataset19)
```

```{r, message=FALSE}
dataset20 <- three_circulars_with_noise(sample_size = 300, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)


langevitour::langevitour(dataset20)
```

```{r, message=FALSE}
dataset21 <- cluster_and_curvilinear__with_noise_and_bkg_noise(sample_size = 260, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)


langevitour::langevitour(dataset21)
```

```{r, message=FALSE}
dataset22 <- link_data_with_noise(sample_size = 300, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset22)
```

```{r, message=FALSE}
dataset23 <- swiss_roll_with_noise(sample_size = 300, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset23)
```

```{r, message=FALSE}
dataset24 <- curvy_tree_with_noise(sample_size = 300, num_of_noise_dim = 1,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset24)
```

```{r, message=FALSE}
dataset25 <- tree_with_noise(sample_size = 500, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset25)
```

```{r, message=FALSE}
dataset26 <- cell_cycle_with_noise(sample_size = 300, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset26)
```

```{r, message=FALSE}
dataset27 <- curvy_cell_cycle_with_noise(sample_size = 300, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset27)
```

```{r, message=FALSE}
dataset28 <- two_curvy_panckakes_with_noise(sample_size = 300, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset28)
```

```{r, message=FALSE}
dataset29 <- small_big_sphere_with_noise(sample_size = 390, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset29)
```

```{r, message=FALSE}
dataset30 <- seven_branching_data_with_noise(sample_size = 420, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset30)
```

```{r, message=FALSE}
dataset31 <- four_branching_data_with_noise(sample_size = 400, num_of_noise_dim = 3,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset31)
```

```{r, message=FALSE}
dataset32 <- eight_branching_data_with_noise(sample_size = 400, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset32)
```

```{r, message=FALSE}
# dataset33 <- one_doublet_with_noise(sample_size = 220, num_of_noise_dim = 6,
#     min_noise = -0.05, max_noise = 0.05)
# 
# langevitour::langevitour(dataset33)
```

```{r, message=FALSE}
dataset34 <- two_curvilinear_data_with_noise(sample_size = 500, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset34)
```

```{r, message=FALSE}
dataset35 <- sphere_data_with_noise(sample_size = 500, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset35)
```

```{r, message=FALSE}
dataset36 <- three_doublets_with_noise(sample_size = 210, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset36)
```

```{r, message=FALSE}
# dataset37 <- one_doublet_four_clusters_with_noise(sample_size = 440, num_of_noise_dim = 6,
#     min_noise = -0.05, max_noise = 0.05)
# 
# langevitour::langevitour(dataset37)
```

```{r, message=FALSE}
# dataset38 <- one_doublet_dfifferent_clusters_with_noise(sample_size = 260, num_of_noise_dim = 6,
#     min_noise = -0.05, max_noise = 0.05)
# 
# langevitour::langevitour(dataset38)
```

```{r, message=FALSE}
dataset39 <- one_doublet_dfifferent_pattern_clusters_with_noise(sample_size = 280, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset39)
```

```{r, message=FALSE}
# dataset40 <- two_doublets_parallel_with_noise(sample_size = 440, num_of_noise_dim = 6,
#     min_noise = -0.05, max_noise = 0.05)
# 
# langevitour::langevitour(dataset40)
```

```{r, message=FALSE}
dataset41 <- one_doublets_with_bkg_noise(sample_size = 250, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset41)
```

```{r, message=FALSE}
dataset42 <- curvy_branching_with_noise(sample_size = 250, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset42)
```

```{r, message=FALSE}
dataset43 <- two_doublets_with_bkg_noise(sample_size = 400, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset43)
```

```{r, message=FALSE}
dataset44 <- two_nonlinear_with_noise(sample_size = 200, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset44)
```

```{r, message=FALSE}
dataset45 <- two_s_curve_hole_with_noise(sample_size = 400, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

dataset45$sample_size

langevitour::langevitour(dataset45$df)
```

```{r, message=FALSE}
dataset46 <- three_grid_with_noise(n_value = 19, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

dataset46$sample_size

langevitour::langevitour(dataset46$df)
```

```{r, message=FALSE}
dataset47 <- one_grid_diff_with_bkg_noise(n_value = 25, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

dataset47$sample_size

langevitour::langevitour(dataset47$df)
```

```{r, message=FALSE}
dataset48 <- two_grid_with_bkg_noise(n_value = 10, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

dataset48$sample_size

langevitour::langevitour(dataset48$df)
```

```{r, message=FALSE}
dataset49 <- traingular_3D_with_noise(sample_size = 500, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset49)
```


```{r, message=FALSE}
dataset54 <- three_linear_with_noise(sample_size = 150, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset54)
```


```{r, message=FALSE}
dataset55 <- three_nonlinear_with_noise(sample_size = 150, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset55)
```


```{r, message=FALSE}
dataset56 <- three_cluster_mirror_with_noise(sample_size = 150, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset56)
```

```{r, message=FALSE}
dataset57 <- s_curve_with_noise(sample_size = 200, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset57)
```

```{r, message=FALSE}
dataset58 <- mobius_cluster_with_noise(sample_size = 250, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset58)
```

```{r, message=FALSE}
dataset59 <- four_long_clusters_with_bkg_noise(sample_size = 150, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset59)
```

```{r, message=FALSE}
dataset60 <- curvy_branching_cluster_with_bkg_noise(sample_size = 200, num_of_noise_dim = 6,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset60)
```

```{r, message=FALSE}
dataset61 <- three_diff_linear_with_noise(sample_size = 300, num_of_noise_dim = 8,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset61)
```

```{r, message=FALSE}
dataset62 <- four_diff_long_clutsers_with_noise(sample_size = 400, num_of_noise_dim = 8,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset62)
```

```{r, message=FALSE}
dataset63 <- two_s_curves_with_noise(sample_size = 400, num_of_noise_dim = 5,
    min_noise = -0.05, max_noise = 0.05)

langevitour::langevitour(dataset63)
```

```{r, message=FALSE}
dataset64 <- plane_2D_with_hole(sample_size = 400, with_seed = 2023062801)

dataset64$sample_size

langevitour::langevitour(dataset64$df)
```

```{r, message=FALSE}
# mirror_s_curves_df <- mirror_s_curves_with_noise(sample_size = 400, num_of_noise_dim = 5,
#     min_noise = -0.05, max_noise = 0.05)
# 
# langevitour::langevitour(mirror_s_curves_df)
```









