# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_highd_dist <- function(test_data, centroids) {
    .Call(`_quollr_compute_highd_dist`, test_data, centroids)
}

compute_errors <- function(true_data, pred_data) {
    .Call(`_quollr_compute_errors`, true_data, pred_data)
}

calc_2d_dist_cpp <- function(x_from, y_from, x_to, y_to) {
    .Call(`_quollr_calc_2d_dist_cpp`, x_from, y_from, x_to, y_to)
}

