# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_emb_indices <- function(test_data, centroids) {
    .Call(`_quollr_predict_emb_indices`, test_data, centroids)
}

compute_errors <- function(true_data, pred_data) {
    .Call(`_quollr_compute_errors`, true_data, pred_data)
}

